# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


### This was my first dive into Numpy, which I thoroughly enjoyed. Numpy might be one of my new favorite python experiences! My variable names and such get a little silly about half way through this assignment, because let's be honest, this was A LOT. But I truly enjoyed the assignment!

In [77]:
!pip install jovian --upgrade --quiet

In [78]:
import jovian

In [79]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "evanmarie/100-numpy-exercises"
[jovian] Committed successfully! https://jovian.ai/evanmarie/100-numpy-exercises


'https://jovian.ai/evanmarie/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [80]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [81]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [110]:
print(np.__version__)
print(np.__config__.show())

1.20.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
array_1 = np.zeros(10)
array_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
array_1.itemsize * array_1.size # Each float takes up 8 bytes times 10

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
array_2 = np.zeros(10)
array_2[4] = 1
array_2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
array_3 = np.arange(10, 50)
array_3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
array_3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
array_4 = np.arange(0, 9).reshape(3, 3)
array_4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
arr_example = np.array([1,2,0,0,4,0])

print(np.where(arr_example == 0))


(array([2, 3, 5]),)


Save your progress by commiting your work to Jovian

In [18]:
import jovian

In [19]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "evanmarie/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/evanmarie/numpy-100-exercises


'https://jovian.ai/evanmarie/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
random_array = np.random.random((3, 3, 3))
random_array

array([[[0.19850512, 0.00964888, 0.10568904],
        [0.73420047, 0.4867579 , 0.63050892],
        [0.96879387, 0.51525811, 0.67944852]],

       [[0.34238019, 0.94720966, 0.46233957],
        [0.87591195, 0.70529463, 0.26642908],
        [0.98817607, 0.2292137 , 0.7387402 ]],

       [[0.20370091, 0.06154962, 0.74795698],
        [0.86172547, 0.51455635, 0.57400702],
        [0.82936599, 0.49070134, 0.31329223]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
random10 = np.random.random((10, 10))
print(random10.min(), random10.max())

0.00033851810711504893 0.9965136001916162


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
thirty = np.random.random(30)
print(thirty.mean())

0.498162578683955


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
two_d = np.zeros((5, 5))
two_d[0] = 1
two_d[-1] = 1
two_d[:,0] = 1
two_d[:, -1] = 1
two_d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [25]:
zeros_array = np.zeros((7, 7))
zeros_array[1:-1, 1:-1] = two_d
zeros_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

0 * np.nan is nan <br>
np.nan == np.nan is False<br>
np.inf > np.nan is False<br>
np.nan - np.nan is nan<br>
np.nan in set([np.nan]) is True ({nan})<br>
0.3 == 3 * 0.1 is False (is 0.30000000000000004)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [26]:
five_squared = np.diag([1, 2, 3, 4], -1)
five_squared

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [27]:
eights2 = np.zeros((8, 8))
np.tile(np.eye(2), (4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
crazy_array = np.arange(1, (6*7*8 + 1)).reshape(6, 7, 8)
crazy_array


array([[[  1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29,  30,  31,  32],
        [ 33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55,  56]],

       [[ 57,  58,  59,  60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69,  70,  71,  72],
        [ 73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88],
        [ 89,  90,  91,  92,  93,  94,  95,  96],
        [ 97,  98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111, 112]],

       [[113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128],
        [129, 130, 131, 132, 133, 134, 135, 136],
        [137, 138, 139, 140, 141, 142, 143, 144],
        [145, 146, 147, 148, 149, 150, 151, 152],
        [153, 154, 155, 156, 157, 158, 159, 16

In [29]:
crazy_array[1, 5, 3]

100

Save your progress by commiting your work to Jovian

In [30]:
import jovian

In [31]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "evanmarie/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/evanmarie/numpy-100-exercises


'https://jovian.ai/evanmarie/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
eights2 = np.zeros((8, 8))
np.tile(np.eye(2), (4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [33]:
rando = np.random.random((5, 5))
rando

array([[0.44580707, 0.57502738, 0.5888955 , 0.06127456, 0.24232189],
       [0.85266269, 0.56492298, 0.30518092, 0.51954604, 0.63795381],
       [0.35370109, 0.45429207, 0.93720231, 0.65250434, 0.85917984],
       [0.35629031, 0.60409602, 0.49500875, 0.48083454, 0.26082955],
       [0.49279586, 0.95755474, 0.98170708, 0.18931823, 0.98689634]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [34]:
my_datatype = np.dtype(('i4', [('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]))
myarray = np.array(0x12345678, dtype = my_datatype)
myarray['red']

array(120, dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
five_three = np.arange(15).reshape(5, 3)
three_two = np.arange(6).reshape(3, 2)
together = np.dot(five_three, three_two)
together

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [36]:
negate_me = np.arange(15)

# getting indices of integers between 3 and 8 and setting them to new values
negate_me[np.logical_and(negate_me>3, negate_me<8)] = -negate_me[np.logical_and(negate_me>3, negate_me<8)]
negate_me

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
messing_around = np.arange(27).reshape(3, 3, 3)

messing_around

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
messing_around[np.logical_and(messing_around > 10, messing_around < 20)] = -messing_around[np.logical_and(messing_around > 10, messing_around < 20)]

In [39]:
messing_around

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10, -11],
        [-12, -13, -14],
        [-15, -16, -17]],

       [[-18, -19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]]])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [40]:
Z**Z - legal
2 << Z >> 2 - legal
Z <- Z - legal
1j*Z - legal
Z/1/1 - legal
Z<Z>Z - not legal

SyntaxError: invalid syntax (2362510792.py, line 6)

In [41]:
z = np.array([1, 2, 3, 4, 5])


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) / np.array(0) - nan
np.array(0) // np.array(0) - 0
np.array([np.nan]).astype(int).astype(float) - array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [42]:
floaties = np.array([1.23, 2.22, 3.33, -1.11, 4.44, -5.55])


round_floaties = np.zeros_like(floaties, dtype = int)

round_floaties[floaties >= 0] = np.ceil(floaties[floaties >= 0])
round_floaties[floaties < 0] = np.floor(floaties[floaties < 0])

print("Rounded Floaties: ", round_floaties)

Rounded Floaties:  [ 2  3  4 -2  5 -6]


#### 30. How to find common values between two arrays? (★☆☆)

In [43]:
array_uno = np.arange(15).reshape(3, 5)
array_zwei = np.arange(9).reshape(3, 3)

print("Array Uno: \n", array_uno)
print("Array Zwei: \n", array_zwei)
print("Intersection time: ", np.intersect1d(array_uno, array_zwei))

Array Uno: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Array Zwei: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Intersection time:  [0 1 2 3 4 5 6 7 8]


Save your progress by commiting your work to Jovian

In [44]:
import jovian

In [45]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "evanmarie/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/evanmarie/numpy-100-exercises


'https://jovian.ai/evanmarie/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [46]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No, np.sqrt(-1) == nan, and np.emath.sqrt(-1) == 1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [47]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Today is ", today)
print('Tomorrow is ', tomorrow)
print('Yesterday was ', yesterday)

Today is  2022-09-06
Tomorrow is  2022-09-07
Yesterday was  2022-09-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [48]:
np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [49]:
a = np.random.random((3,3))
b = np.random.random((3,3))

c = a
print("Before the equation, c: \n", c)
np.multiply(np.multiply(np.add(a, b, out=a), a, out=a), 0.5, out=a)
print("After the equation, c: \n", c)




Before the equation, c: 
 [[0.54199369 0.73523583 0.1582846 ]
 [0.74767132 0.68661553 0.28255951]
 [0.06694817 0.26148869 0.19346578]]
After the equation, c: 
 [[0.85803092 0.70460062 0.59382685]
 [0.89784795 0.50576909 0.09696205]
 [0.52071283 0.34422559 0.40109776]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [51]:
best_array = np.random.random((3, 3))
print("best_array OG: \n", best_array)
print("np.round: \n", np.round(best_array))
print('np.ceil: \n', np.ceil(best_array))
print('np.floor: \n', np.floor(best_array))
print('dtype = int: \n', np.array(best_array, dtype = int))

best_array OG: 
 [[0.66221418 0.73239889 0.52296533]
 [0.20069796 0.05912904 0.11679739]
 [0.31273546 0.54802996 0.08372067]]
np.round: 
 [[1. 1. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]
np.ceil: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.floor: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
dtype = int: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [52]:
more_fives = np.zeros((5, 5))
print("Array before: \n", more_fives)

more_fives += np.arange(5)
print("Array after: \n", more_fives)

Array before: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array after: 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [53]:
def number_maker():
    for number in range(11):
        yield number
        
generated_array = np.fromiter(number_maker(), dtype=int)

print("Tada! An generated array! \n", generated_array)

Tada! An generated array! 
 [ 0  1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [54]:
skinny_array = np.linspace(0,1,12)[1:-1]
print(skinny_array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [55]:
rando_dando = np.random.random(10)
rando_dando.sort()
print(rando_dando)

[0.02403261 0.50761808 0.5484412  0.58432952 0.68199952 0.7497707
 0.76654717 0.88180687 0.89915204 0.99256125]


Save your progress by commiting your work to Jovian

In [56]:
import jovian

In [57]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "evanmarie/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/evanmarie/numpy-100-exercises


'https://jovian.ai/evanmarie/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [58]:
%%time
sum_me = np.arange(15)
sum = np.add.reduce(sum_me)

CPU times: user 58 µs, sys: 14 µs, total: 72 µs
Wall time: 51.7 µs


In [59]:
%%time
sum_me = np.arange(15)
sum = np.sum(sum_me)

CPU times: user 84 µs, sys: 20 µs, total: 104 µs
Wall time: 73 µs


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
%%time
random_a_array = np.random.random((3, 3))
random_b_array = np.random.random((3, 3))

print("It is very unlikely this will be True. It is ", np.all(random_a_array == random_b_array))

It is very unlikely this will be True. It is  False
CPU times: user 422 µs, sys: 102 µs, total: 524 µs
Wall time: 325 µs


In [61]:
%%time
random_a_array = np.random.random((3, 3))
random_b_array = np.random.random((3, 3))

print("It is very unlikely this will be True. It is ", np.array_equal(random_a_array, random_b_array))

It is very unlikely this will be True. It is  False
CPU times: user 647 µs, sys: 157 µs, total: 804 µs
Wall time: 478 µs


#### 43. Make an array immutable (read-only) (★★☆)

In [62]:
immute_me = np.random.random((5, 5))

immute_me.flags.writeable = False
# immute_me[1] = 5 
# This produces a ValueError

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [63]:
cartesians = np.random.random((10, 2))

x,y = cartesians.T
radius = np.sqrt(np.sum(cartesians*cartesians, 1))
theta = np.arctan(y, x)
theta[x<0] += np.pi

polars = np.vstack((radius, theta)).T
print("Polars: \n", polars)


Polars: 
 [[1.27515662 0.73976411]
 [0.54925144 0.39801951]
 [0.23653274 0.01029341]
 [0.27164798 0.09496444]
 [0.36780169 0.05331711]
 [1.03308727 0.69409103]
 [1.01639692 0.5122008 ]
 [1.24331596 0.64220638]
 [0.9171994  0.61102944]
 [0.92459774 0.74527171]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
limit_my_max = np.random.randn(10)
print("Before: ", limit_my_max)
limit_my_max[limit_my_max.argmax()] = 0
print("After: ", limit_my_max)

Before:  [-2.00091912  0.53256148 -1.30533324  0.49131961  0.38876112  0.68220756
  1.11240392 -0.91431662 -0.66670342  1.13805664]
After:  [-2.00091912  0.53256148 -1.30533324  0.49131961  0.38876112  0.68220756
  1.11240392 -0.91431662 -0.66670342  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [65]:
meshy_array = np.zeros((5,5), [("x", float), ("y", float)])
meshy_array['x'], meshy_array['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))

print("Meshy Coordinates: \n", meshy_array['x'], meshy_array['y'])

Meshy Coordinates: 
 [[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]] [[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [66]:
x_boy = np.arange(5, 25, 2)
y_girl = np.arange(25, 45, 2).reshape(-1,1)

cauchy = 1.0 / (x_boy - y_girl)

print("My Cauchy: \n", cauchy)

My Cauchy: 
 [[-0.05       -0.05555556 -0.0625     -0.07142857 -0.08333333 -0.1
  -0.125      -0.16666667 -0.25       -0.5       ]
 [-0.04545455 -0.05       -0.05555556 -0.0625     -0.07142857 -0.08333333
  -0.1        -0.125      -0.16666667 -0.25      ]
 [-0.04166667 -0.04545455 -0.05       -0.05555556 -0.0625     -0.07142857
  -0.08333333 -0.1        -0.125      -0.16666667]
 [-0.03846154 -0.04166667 -0.04545455 -0.05       -0.05555556 -0.0625
  -0.07142857 -0.08333333 -0.1        -0.125     ]
 [-0.03571429 -0.03846154 -0.04166667 -0.04545455 -0.05       -0.05555556
  -0.0625     -0.07142857 -0.08333333 -0.1       ]
 [-0.03333333 -0.03571429 -0.03846154 -0.04166667 -0.04545455 -0.05
  -0.05555556 -0.0625     -0.07142857 -0.08333333]
 [-0.03125    -0.03333333 -0.03571429 -0.03846154 -0.04166667 -0.04545455
  -0.05       -0.05555556 -0.0625     -0.07142857]
 [-0.02941176 -0.03125    -0.03333333 -0.03571429 -0.03846154 -0.04166667
  -0.04545455 -0.05       -0.05555556 -0.0625    ]
 [-0

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [67]:
for dtype in [np.int8, np.int32, np.int64]:
    print("np.iinfo(dtype): \n", np.iinfo(dtype))

np.iinfo(dtype): 
 Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

np.iinfo(dtype): 
 Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

np.iinfo(dtype): 
 Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆)

In [68]:
print_me = np.arange(3, 33, 3)
np.set_printoptions(threshold=np.inf)

print(print_me)

[ 3  6  9 12 15 18 21 24 27 30]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [69]:
fred = np.arange(100)
albert = np.random.uniform(0, 100)
chelsea = np.abs(fred - albert).argmin()

print("Voila! ", fred[chelsea])

Voila!  2


Save and commit your work.

In [70]:
import jovian

In [71]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "evanmarie/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/evanmarie/numpy-100-exercises


'https://jovian.ai/evanmarie/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [72]:
data = np.zeros(3, dtype=[('position', [ ('x', float),   
                                            ('y', float)]),
                                ('color',    [ ('r', float),
                                            ('g', float),
                                            ('b', float)])])

print("Structured array with x,y and a color: \n", data)

Structured array with x,y and a color: 
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [73]:
# Use np.atleast_2d to convert both vectors to 2D
# Use broadcasting to subtract vector_2 from vector_1
# Use np.square to square the difference matrix
# Use np.sum to sum the squared difference matrix
# Use np.sqrt to take the square root of the sum
# Use np.squeeze to remove the last dimension

vector_1 = np.random.random((100, 2))
vector_2 = np.random.random((100, 2))
np.atleast_2d(vector_1, vector_2)

distances = np.sqrt(np.sum(np.square(vector_1 - vector_2), axis = 1))
print("distances: \n", distances)

distances: 
 [0.37500514 0.40194236 0.87408422 0.36504844 0.25690948 0.43830842
 0.29931605 0.44108131 0.82064161 0.24875154 0.25418197 0.79636346
 0.76734041 0.91839932 0.33154296 0.90060696 0.29553676 0.36634957
 0.62841239 0.70250195 0.50243344 0.88653035 0.18417443 0.16241003
 0.39532677 0.45180055 0.93805795 0.14490657 0.23748043 0.20604392
 0.87313928 0.66615308 0.17292354 0.27489274 1.13487026 0.27018671
 1.098745   0.8094849  0.94058422 0.84229834 0.16301062 0.78206235
 0.77743234 0.30916985 0.47095811 0.54619457 0.60406344 0.54795786
 0.18226784 0.43539416 0.83338138 0.8537773  0.97472522 0.35584677
 0.43166337 0.08900545 0.46872347 0.71792729 0.79601286 0.19556448
 0.98615029 0.73866868 0.31051881 1.02478305 0.60000085 0.45677661
 0.46391797 0.61743916 0.57997856 0.6898347  0.32225085 0.18407733
 0.86593103 0.44238151 0.20921601 0.4421152  0.58563656 0.79281233
 0.10533349 0.61292223 0.49194887 1.18678628 0.05927907 0.77785762
 0.86884598 0.93357024 0.58938209 0.39165922 0.61

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [74]:
# Use the astype method to convert the data type of the array

floats_away = np.arange(10, dtype = np.float32)
floats_converted = floats_away.astype(np.int32, copy = False)
print("floats_converted: \n", floats_converted)


floats_converted: 
 [0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [75]:
from io import StringIO # StringIO behaves like a file object

In [76]:

string_to_read = StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')

numbers_to_read = np.genfromtxt(string_to_read, delimiter = ",", dtype = int)
print("numbers_to_read: \n", numbers_to_read)

numbers_to_read: 
 [[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [84]:
np.ndenumerate
# Example:
np.ndenumerate(numbers_to_read)
# Creates a ndenumerate object that can be iterated over

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [86]:
# Use np.meshgrid to create a rectangular grid out of an array of x values and an array of y values
# Use the standard equation for a 2D Gaussian to compute the height of each point on the grid
# Use np.exp to compute the exponential of all elements in the array
# Use np.sqrt to compute the square root of all elements in the array

x = np.linspace(-1, 1, 10)
y = np.linspace(-1, 1, 10)
x,y = np.meshgrid(x, y)
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d-mu)**2 / (2.0 * sigma**2)))
print("g: \n", g)

g: 
 [[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [88]:
# Use np.put to randomly place p elements in an array
# Use np.random.choice to generate p unique indices
# Use np.put to place p elements in the array at the indices generated by np.random.choice
# OR
# Use np.putmask to place p elements in the array at random locations

my_number = 3
my_random_array = np.zeros((5, 5))
np.put(my_random_array, np.random.choice(range(5*5), my_number, replace = False), 1)
print("my_random_array: \n", my_random_array)

# OR

my_random_array2 = np.zeros((5, 5))
np.putmask(my_random_array2, np.random.rand(5, 5) < 0.5, 1)
print("my_random_array2: \n", my_random_array2)


my_random_array: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
my_random_array2: 
 [[1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1.]
 [0. 1. 0. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [89]:
# Subtract the mean of each row of a matrix
# Use np.mean to compute the mean of the flattened array
# Use broadcasting to subtract the mean from each row

my_matrix = np.random.rand(5, 10)
my_matrix_mean = my_matrix - my_matrix.mean(axis = 1, keepdims = True)
print("my_matrix_mean: \n", my_matrix_mean)

my_matrix_mean: 
 [[-0.087331    0.28045704  0.09884103  0.24028911 -0.05410158 -0.54227666
  -0.44091135  0.09796806  0.36679186  0.0402735 ]
 [-0.33913262  0.46283841 -0.41976427 -0.44509772  0.1420593   0.15908923
  -0.19847702  0.43547772  0.44190862 -0.23890165]
 [ 0.06450739 -0.34022669 -0.30249776 -0.10469277  0.16732515 -0.25225626
  -0.05973743  0.29430727  0.19188914  0.34138195]
 [-0.31738591  0.41807973  0.26420105 -0.04011138  0.45053307 -0.19966895
  -0.37402804 -0.14936405  0.08661854 -0.13887405]
 [ 0.21240694  0.29108887  0.41998414 -0.35085964 -0.09182055 -0.18847607
  -0.48727223 -0.09486634  0.25774539  0.03206949]]


#### 59. How to sort an array by the nth column? (★★☆)

In [91]:
def sort_me_baby(array, n):
    return array[np.argsort(array[:, n])]

array_to_sort = np.random.randint(0, 10, (5, 5))

print("sort_me_baby(array_to_sort, 3): \n", sort_me_baby(array_to_sort, 3))

sort_me_baby(array_to_sort, 3): 
 [[8 7 5 0 9]
 [6 2 6 4 7]
 [1 5 6 5 1]
 [2 0 9 8 8]
 [1 8 5 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [106]:
my_array_to_investigate = np.random.randint(0, 10, (6, 10))


print("my_array_to_investigate: \n", my_array_to_investigate)
print('\n')
print("Array has null columns? \n", 
      (my_array_to_investigate.all(axis = 0)).any())
print('\n')


my_array_to_investigate: 
 [[7 5 3 7 3 8 1 0 9 2]
 [1 0 3 9 0 8 9 0 6 5]
 [6 5 5 0 0 2 7 4 6 7]
 [4 2 6 7 4 7 8 8 6 3]
 [7 9 1 0 6 2 2 1 4 1]
 [6 0 5 8 4 6 5 0 1 9]]


Array has null columns? 
 True




Save and commit your work.

In [14]:
import jovian

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

In [108]:
# Use np.abs to compute the absolute value of the difference between the value and each element 
# in the array
# Use np.argmin to return the indices of the minimum values along the given axis

my_array_to_search = np.random.randint(0, 10, 10)
search_value = 5
results = my_array_to_search[np.abs(my_array_to_search - search_value).argmin()]

print("my_array_to_search: \n", my_array_to_search)
print("results: \n", results)


my_array_to_search: 
 [0 0 3 8 9 6 0 9 8 9]
results: 
 6


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [112]:
# Use np.nditer to iterate over the arrays

array_3_1 = np.arange(3).reshape(3, 1)
array_1_3 = np.arange(3).reshape(1, 3)
array_sum = np.nditer([array_3_1, array_1_3, None])
print("array_3_1: \n", array_3_1, "\n")
print("array_1_3: \n", array_1_3, "\n")
print("array_sum: \n", [array_sum.operands[2] for a, b, c in array_sum if c == a + b], "\n")

array_3_1: 
 [[0]
 [1]
 [2]] 

array_1_3: 
 [[0 1 2]] 

array_sum: 
 [] 



#### 63. Create an array class that has a name attribute (★★☆)

In [116]:
# Use a class to create an array with a name attribute
# Use the __array_finalize__ method to set the name attribute of the returned array

class MyArrayClass(np.ndarray):
    def __new__(cls, array, name = 'a_name'):
        object = np.asarray(array).view(cls)
        object.name = name
        return object
    
    def __array_finalize__(self, object):
        if object is None: return
        self.info = getattr(object, 'name', 'a_name')

a_classy_array = MyArrayClass(np.arange(10), name = 'a_classy_array')

print("a_classy_array: \n", a_classy_array, "\n")

a_classy_array: 
 [0 1 2 3 4 5 6 7 8 9] 



#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [118]:
# Use np.add.at to add 1 to each element of a, at indices in b

little_array_a = np.ones(10)
little_array_b = np.random.randint(0, len(little_array_a), 23)

print("little_array_a: \n", little_array_a, "\n")
print("little_array_b: \n", little_array_b, "\n")

np.add.at(little_array_a, little_array_b, 1)

print("little_array_a: \n", little_array_a, "\n")

little_array_a: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

little_array_b: 
 [8 6 4 5 1 1 0 9 7 0 0 3 1 1 5 1 6 4 0 1 9 5 6] 

little_array_a: 
 [5. 7. 1. 2. 3. 4. 4. 2. 2. 3.] 



#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [119]:
# Use np.bincount to count the number of occurrences of each value in an array of non-negative
# ints

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
i = [7, 4, 7, 1, 2, 3, 9, 3, 9, 3]
f = np.bincount(i, weights = x)

print("x: \n", x, "\n")
print("i: \n", i, "\n")
print("f: \n", f, "\n")

x: 
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

i: 
 [7, 4, 7, 1, 2, 3, 9, 3, 9, 3] 

f: 
 [ 0.  4.  5. 24.  2.  0.  0.  4.  0. 16.] 



#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [16]:
import jovian

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [18]:
import jovian

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100