# Intermediate Python
### Patrick Loeber, python-engineer.com
### https://www.youtube.com/watch?v=HGOBQPFzWKo
(2:59:40)
September 17, 2022

## RANDOM NUMBERS:
We will look at the random module for pseudo-random numbers, the secrets module for cryptographically strong random numbers, and the numpy random module for generating arrays with random numbers

In [6]:
# used to generate pseudo random numbers,
# which can actually be reproduced
import random

In [13]:
# random = random float in range 0-1 by default

a = random.random()
print(a)

0.6833427868153528


In [14]:
# uniform = allows you to give a range for random float

b = random.uniform(1, 10)
print(b)

8.832407107566208


In [15]:
# randint = you can give a range and get an int
# includes upper bound

c = random.randint(1, 10)
print(c)

4


In [16]:
# randrange = gives int, but does not include the upper bound

d = random.randrange(1, 10)
print(d)

9


In [17]:
# normalvariate returns a random number from a normal distribution
# with the given mean (mu) and standard deviation (sigma)
# useful with statistics

e = random.normalvariate(0, 1)
print(e)

0.6394149642131549


### Random Module -> functions to work with sequences:

In [18]:
# .choice() chooses a random element from a sequence

list01 = list('ABCDEFGHIJKLMNO')
f = random.choice(list01)
print(f)

E


In [19]:
# .sample() takes a number of elements and give that many back
# chooses unique elements, no duplicates

g = random.sample(list01, 2)
print(g)

['D', 'E']


In [21]:
# .choices() will return multiple elements and allow for duplicates

h = random.choices(list01, k = 3)
print(h)

['A', 'B', 'A']


In [22]:
# .shuffle() will shuffle a list in place, saved to the sequence

i = random.shuffle(list01)
print(list01)

['C', 'G', 'D', 'H', 'B', 'E', 'A', 'F']


In [26]:
# .seed() sets the seed for the random number generator to the
# given value, used to make the random number generator
# repeatable. If you don't call it, the seed is set to the current time, so you get a different sequence of random numbers each time
# you run the program

random.seed(1)
print(random.random())
print(random.randint(1, 10))

random.seed(1)
print(random.random())
print(random.randint(1, 10))

random.seed(2)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2
0.13436424411240122
2
0.9560342718892494
1


### Truly Random
Use the secrets module for security for things like passwords, etc.
The downside is the time it takes, but will generate a truly random number.

The secrets module provides access to the most secure source of
randomness that your operating system provides. It is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.

If you don't have access to the operating system's random number generator, it uses the random module to generate random numbers.

* .randbelow() returns a random integer in the range [0, n)
* .choice()  returns a random element from a non-empty sequence
* .randbelow() returns a random int in the range [0, n)
* .randbits() returns an int with k random bits
* .SystemRandom() class from the secrets module returns a random number generator using the system's best random source

In [27]:
import secrets

In [28]:
# .randbelow() takes an upperbound argument, not included

j = secrets.randbelow(10)
print(j)

3


In [29]:
# .randbits() takes an argument for the number of random bits,
# random binary values

k = secrets.randbits(4)
print(k)

4


In [31]:
# .choice()
list02 = list('ABCDEFGHIJKLMNO')
l = secrets.choice(list02)
print(l)

B


### NUMPY Random Module: uses a different random number generator than that of the standard Python library.
*  np.random() returns a random number from a uniform distribution

* np.random.seed() sets the seed for the random number generator to the given value

* np.random.randn() returns a random number from a normal distribution with mean 0 and standard deviation 1

* np.random.randint() returns a random integer in the range [low, high) where low and high are the arguments to the function

* np.random.choice() returns a random element from a sequence the sequence is the argument to the function

* np.random.shuffle() shuffles a sequence in place the sequence is the argument to the function

* np.random.permutation() returns a random permutation of a sequence the sequence is the argument to the function

In [32]:
import numpy as np

In [38]:
# np.random.rand()
# produce a 1d array of random floats the size as passed

m = np.random.rand(3)
print(m)

[0.07680321 0.14062698 0.52764071]


In [39]:
# np.random.rand()
# produce and array of random floats of the size passed

n = np.random.rand(3, 3)
print(n)

[[0.62075546 0.60722106 0.84988571]
 [0.27967633 0.07165339 0.86061931]
 [0.32373108 0.32767428 0.6005563 ]]


In [41]:
# np.random.randint()
# produce an array of random integers
# arguments are start, end (exclusive), and size)

o = np.random.randint(0, 10, 3)
print(o)

[6 7 9]


In [42]:
# using a tuple for the size allows for greater dimensions

p = np.random.randint(0, 10, (3, 4))
print(p)

[[5 2 4 6]
 [6 0 5 0]
 [8 5 1 4]]


In [43]:
# .shuffle() shuffles the elements in place, but only along first
# axis, never between axes

array01 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array01)
np.random.shuffle(array01)
print(array01)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [44]:
# .seed() like the one from the random module, seeds the generator
# preferable over the one from random module

np.random.seed(1)
print(np.random.rand(3,3))

np.random.seed(1)
print(np.random.rand(3,3))

np.random.seed(2)
print(np.random.rand(3,3))

np.random.seed(2)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]
[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]
